name: Build and deploy React app to Azure Web App - echo-ui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
            npm i --package-lock-only
          fi
          npm run build --if-present

      - name: Remove unnecessary files
        run: rm -rf node_modules

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build  # Upload the build folder directly

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: build  # Extract to 'build/' directory

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'echo-ui'
          package: build  # Deploy only the contents of 'build/'

      - name: Set Startup Command (for React)
        run: az webapp config set --name echo-ui --resource-group echo-healthcare-rg --startup-file "npx serve -s ."
